[package]
name = "figment-keyring"
version = "0.1.0"
edition = "2021"

[dependencies]
figment2 = { version = "0.11", features = ["env"] }
serde = { version = "1", features = ["derive"] }
keyring = "4.0.0-rc.3"
keyring-core = "0.7.2"
thiserror = "1"
